runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  login: admin
  http_headers:
    X-Frame-Options: "DENY"
    Strict-Transport-Security: "max-age=2592000; includeSubdomains"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"

- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)
  secure: always
  login: admin
  http_headers:
    X-Frame-Options: "DENY"
    Strict-Transport-Security: "max-age=2592000; includeSubdomains"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"

skip_files:
- .*\.git
- ^src/(.*)
- ^node_modules/(.*/)?
- ^.babelrc$
- ^.editorconfig$
- ^.gitignore$
- ^.stylelintrc$
- ^app\.(.*)\.yaml$
- ^global\.d\.ts$
- ^package-lock\.json$
- ^package\.json$
- ^README\.md$
- ^tsconfig\.json$
- ^tslint\.json$
- ^webpack\.common\.js$
- ^webpack\.dev\.js$
- ^webpack\.prod\.js$
