image: node:8

pipelines:
  default:
    - step:
      name: install
        script:
          - npm install
        caches:
          - node_modules
    - step:
        name: lint
        script:
          - npm run lint
        caches:
          - node_modules
    - step:
        name: test
        script:
          - npm test
        caches:
          - node_modules
    - step:
        name: build
        script:
          - npm run build
        caches:
          - node_modules
        artifacts:
          - dist/**
    - step:
        name: deploy
        image: google/cloud-sdk
        script:
          - echo "$GAE_KEY" > /tmp/gae_key.json
          - gcloud config set project $GAE_PROJECT
          - gcloud auth activate-service-account --key-file /tmp/gae_key.json
          - gcloud --quiet app deploy app.yaml --version $BITBUCKET_BRANCH
          - rm /tmp/gae_key.json
